#Include alpine_run\main.ahk
#Include candy_falls\main.ahk
#Include carved\main.ahk
#Include cubism\main.ahk
#Include end_of_the_road\main.ahk
#Include four_circles\main.ahk
#Include frozen_over\main.ahk
#Include hedge\main.ahk
#Include in_the_loop\main.ahk
#Include logs\main.ahk
#Include lotus_island\main.ahk
#Include middle_of_the_road\main.ahk
#Include monkey_meadow\main.ahk
#Include one_two_tree\main.ahk
#Include park_path\main.ahk
#Include resort\main.ahk
#Include scrapyard\main.ahk
#Include skates\main.ahk
#Include spa_pits\main.ahk
#Include the_cabin\main.ahk
#Include tinkerton\main.ahk
#Include town_center\main.ahk
#Include tree_stump\main.ahk
#Include winter_park\main.ahk

